# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DL_tasks',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/DL_tasks',
                'lib_path': 'DL_tasks'},
  'syms': {}}
